### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by sean-rohan-NOAA** [alaska-groundfish-efh/EFHSDM#13]
Should the repo include the queries that were used to retrieve and pre-process EFH data?

**Comment by MargaretSiple-NOAA** [comment]
Yes I think this is a brilliant idea! Thank you Sean (and sorry I think this escaped my attention). Especially for the covariate rasters, it would be good to include. 

I am tagging Jeremy just so he is aware, but Jeremy I can totally help with this too.

**Comment by MargaretSiple-NOAA** [comment]
Adding as a note to myself here to find the code for partitioning survey catches into different age classes and add them to this pkg.

**Comment by MargaretSiple-NOAA** [comment]
This is related to #11 , advancements for the next review

**Comment by MargaretSiple-NOAA** [comment]
We made a new repo alaska-groundfish-efh/data-acquisition-prep that will contain the steps for pulling tables from AKFIN and building the tables for fitting the SDMs, so closing this one!
