### ISSUE TITLE
rgdal dependency

### ISSUE THREAD

**Issue by James-Thorson-NOAA** [alaska-groundfish-efh/EFHSDM#20]
Hi all,

I'm using R 4.3.2 and trying to install the main branch using `devtools::install_github("alaska-groundfish-efh/EFHSDM@main")` as per README instructions.  It then throws an error related to `rgdal` not being available.  Do y'all already have a fix for this that I'm not seeing?

And sorry to ask ... obviously the rgdal deprecation has been super-annoying :0

Jim

**Comment by sean-rohan-NOAA** [comment]
Hi Jim,

Just seeing this issue. No, this hasn't been fixed yet and we currently don't have a timeline for making the change. There will clearly need to be some pretty sweeping changes to address the obsolescence of rgdal and rgeos.

Sean

**Comment by krtanaka-NOAA** [comment]
Hi, 
Are there any updates on the issue related to the rgdal dependency for installing the EFHSDM? I'm still trying to find my way around the rgdal retirement as well.
Thanks

**Comment by MargaretSiple-NOAA** [comment]
Hi Jim -- I didn't forget about this! Just merged a PR that deals with these spatial dependencies including `rgdal`. There's still a lot more testing I'd like to do, but I have captured that in other issues.

**Comment by James-Thorson-NOAA** [comment]
Thanks for the update!  I certainly realize that it's been a lot of work keeping up with the sp/rgdal retirement :0

**Comment by MargaretSiple-NOAA** [comment]
No problem! It is part of our jobs. I should specify that the additional testing we need is just general unit tests, not anything specific to `terra` necessarily. Both Sean and I have been able to run the full script from the examples with the new spatial updates.
