### ISSUE TITLE
Unknown bug in vignette with MakeMaxEntAbundance() - pkgdev branch

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [alaska-groundfish-efh/EFHSDM#6]
I have put the content of `R/Vignette.R` into `vignettes/BasicsOfFiveYearReview.Rmd` and  am getting an error at [this line](https://github.com/alaska-groundfish-efh/EFHSDM/blob/132328713c17bcb7cdf99ed563512d2fd281c597/vignettes/BasicsOfFiveYearReview.Rmd#L118) when I try to run it. I can come back to it later but am stumped right now. The error is:

```r
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'isTRUE': error in evaluating the argument 'current' in selecting a method for function 'all.equal': unable to find an inherited method for function ‘extent’ for signature ‘"NULL"’
```

Will check the functions and come back to this but might need Jeremy help.

**Comment by jeremyharris7** [comment]
I think I've fixed it. Try again and let me know if the same problem shows up.

**Comment by MargaretSiple-NOAA** [comment]
I tried it and it's fixed now! Thanks.
