### ISSUE TITLE
Include informative warnings or suppress warnings in fit functions?

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [alaska-groundfish-efh/EFHSDM#7]
While testing the vignette I noticed that many of the fitting functions throw a bunch of warnings, like these:
![image](https://user-images.githubusercontent.com/73858992/159285881-62bf18d2-4869-4de7-b605-7faa4ec26222.png)

I am guessing this comes from some fitting issues that are expected and okay. If this is the case, some of these functions (e.g., `MakeVarianceRasters()` may need to include some conditions inside them that will inform the user of what is happening but don't fill the console with warnings. Silencing warnings would be ok but a brief and informative one is better.

**Comment by jeremyharris7** [comment]
So it's not a fitting issue. Basically, there are a lot of situations where data might be either NA or a raster, and if its the raster it throws a warning. I'll just have to go through and suppress things.

**Comment by MargaretSiple-NOAA** [comment]
Sounds good. Maybe a single warning can show up instead that says something informative like "using data from raster" or "X locations with NA data in this dataset" something like that. So people still know something is happening but it's less verbose.
